kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: Kubernates
    trainer: prashanth
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    images: nginx