kind: Pod
apiVersion: v1
metadata:
  name: annotations
  labels:
    course: Kubernates
    trainer: prashanth
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernates'
    - name: duration
      value: '120hr'  