kind: Pod
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernates'
    - name: duration
      value: '120hr'  