apiVersion: v1
kind: Pod
metadata:
  name: 
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      #limit should be atleast same   
      limits:
        memory: "128Mi"
        cpu: "100m"