kind: Pod
apiVersion: v1

metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      #limit should be atleast same   
      limits:
        memory: "128Mi"
        cpu: "100m"